REQUEST_BODY = "body"
REQUEST_QUERY = "query"
REQUEST_USER = "user"

RESPONSE_BODY = "body"
RESPONSE_SERVICE_MESSAGES = "service_messages"
RESPONSE_INFO = "info"

LITERAL_SEARCH_SYMBOL = ":"

FIREBASE_SERVICE_ACCOUNT_JSON = "keys/alfa-bot-8d9cc-68b0eae3c6c5.json"

DB_USERS_FIELD = "users"

USER_INTEGRATIONS = "integrations"
INTEGRATIONS_SHEETS = "sheets"
INTEGRATION_STATUS_UNDECIDED = "undecided"
INTEGRATION_STATUS_REFUSED = "refused"
INTEGRATION_STATUS_AGREED = "agreed"
INTEGRATION_STATUS_READY = "ready"


DEFAULT_USER_STATUS = {USER_INTEGRATIONS: {INTEGRATIONS_SHEETS: INTEGRATION_STATUS_UNDECIDED}}